# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9f383402d3a60ba3fc999d0ff5fee2c66de88a8f7fbf290c11dbd127777fa7f95795e720b64bc93cf8b34da1f9d5f3e075d6fdac19931dcbf896fa79d1281f8

test:
  secret_key_base: 62a027f675bd423365128db2d92c82d08049290f622436aa5997b150ef6bd5d644d48c17b38e93c14894ac974cf29bc8f11a271315f1eed409dfe5d7902a944d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
